ndt_2d_node:
  ros__parameters:
    enable_mapping: True
    global_search_size: 4.0
    global_search_limit: 3
    minimum_travel_distance: 0.5
    minimum_travel_rotation: 1.0
    # no map_file
    occupancy_threshold: 0.05
    odom_frame: "odom_combined"
    optimization_node_limit: 5
    resolution: 0.05
    robot_frame: "base_link"
    rolling_depth: 10
    transform_timeout: 0.2
    use_barycenter: True
    use_particle_filter: False
    use_sim_time: True
    local_scan_matcher:
      laser_max_beams: 100
      ndt_resolution: 0.25
      search_angular_resolution: 0.0025
      search_angular_size: 0.1
      search_linear_resolution: 0.005
      search_linear_size: 0.1
    global_scan_matcher:
      laser_max_beams: 100
      ndt_resolution: 0.25
      search_angular_resolution: 0.0025
      search_angular_size: 0.2
      search_linear_resolution: 0.01
      search_linear_size: 0.5

